###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis
      container_name: redis
      ports:
       - "6379:6379"

    memcached:
      image: memcached:alpine
      container_name: memcached
      ports:
       - "11211:11211"

    cli:
      build:
        context: .
        dockerfile: ./var/docker/php/Dockerfile
      container_name: cli
      working_dir: /application
      volumes:
        - .:/application
        - ./var/docker/php/conf.d/php.ini:/usr/local/etc/php/php.ini
        - ./var/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini