name: PHP Composer and Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.os }} w/ ${{ matrix.dependencies }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "8.5"
        os: [ubuntu-latest]
        dependencies: ["install", "update"]
    env: 
      extensions: yac, fileinfo, mbstring, apcu
      key: extensions-php

    steps:
      - uses: actions/checkout@main

      - name: Setup PHP
        id: php-env
        uses: shivammathur/setup-php@main
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          
      - name: Cache extensions
        uses: actions/cache@main
        with:
          path: ${{ steps.php-env.outputs.dir }}
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer ${{ matrix.dependencies }} --prefer-dist --no-progress --ignore-platform-reqs
        env:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: yac.enable_cli=On, apc.enabled=On, apc.enable_cli=On

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        env:
          TMPDIR: ${{ runner.temp }}
        run: composer tests
